import { RootProvider } from "./context/rootcontext";
import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer";

//  tous les composants sont enveloppés en tant qu'enfant. Point principal de l'app.

// https://nextjs.org/docs/pages/api-reference/components/link

// export const metadata = {
//   title: "Ma première app. React/NextJS",
//   description: "Generated by create next app",
// };
export const metadata = {
  Home: {
    title: "Ma page d'accueil",
    description: "Description de la page des projets du site",
  },
  BarreDeRecherche: {
    title: "Rechercher sur le site",
    description: "Description de la page recherche sur le site",
  },
  Increment: {
    title: "Likez moi",
    description: "Description de la page d'incrémentation'",
  },
 ExchangeV1: {
    title: "Stock-Exchange Api Version1",
    description: "Description de la page stock Exchange",
  },
  ExchangeV2: {
    title: "Stock-Exchange Api Version2",
    description: "Description de la page stock Exchange",
  },
  Chronometre: {
    title: "Chronomètre",
    description: "Description de la page chronomètre",
  },
  LotoGame: {
    title: "Jeu Loto Système",
    description: "Description de la page Loto système",
  },
  BonneteauGame: {
    title: "Jeu bonneteau",
    description: "Description de la page de contact",
  },
  LotoReglement: {
    title: "Règlement du jeu loto",
    description: "Description de la page réglement du loto",
  },
 BonneteauReglement: {
    title: "Règlement du jeu bonneteau",
    description: "Description de la page réglement du bonneteau",
  },
  Cv: {
    title: "Mon Cv",
    description: "Description de la page Cv",
  },
  Contact: {
    title: "Me contacter",
    description: "Description de la page de contact",
  },
  Admin: {
    title: "Private Admin page",
  },
  Dashboard: {
    title: "Private Dashboard page",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <RootProvider>
          <Header />
          {children}
          <Footer />
        </RootProvider>
      </body>
    </html>
  );
}
