

import { RootProvider } from "./context/rootcontext";
import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer";


//  tous les composants sont enveloppés en tant qu'enfant. Point principal de l'app.

export const metadata = {
  title: "Ma première app. React/NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>       
        <RootProvider> 
          <Header />
        <main className="scrollpages" > {children} 
           <Footer />
           </main>
        </RootProvider>    
       </body>
    </html>
  );
}
